### ISSUE TITLE
Issue when i do the 'info' command

### ISSUE THREAD

**Issue by colbeagle** [DrSkunk/discord-plays-pokemon#2]
Hi, i got a issue when i do the 'info' command.
Here the error.

/home/discord-plays-pokemon/node_modules/discord.js/src/structures/MessageEmbed.js:432
    if (!value) throw new RangeError('EMBED_FIELD_VALUE');
                      ^

RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values may not be empty.
    at Function.normalizeField (/home/discord-plays-pokemon/node_modules/discord.js/src/structures/MessageEmbed.js:432:23)
    at /home/discord-plays-pokemon/node_modules/discord.js/src/structures/MessageEmbed.js:452:14
    at Array.map (<anonymous>)
    at Function.normalizeFields (/home/discord-plays-pokemon/node_modules/discord.js/src/structures/MessageEmbed.js:451:8)
    at MessageEmbed.addFields (/home/discord-plays-pokemon/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/discord-plays-pokemon/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Object.execute (/home/discord-plays-pokemon/dist/commands/Info.js:22:22)
    at DiscordClient.<anonymous> (/home/discord-plays-pokemon/dist/DiscordClient.js:118:33)
    at step (/home/discord-plays-pokemon/dist/DiscordClient.js:33:23)
    at Object.next (/home/discord-plays-pokemon/dist/DiscordClient.js:14:53) {
  [Symbol(code)]: 'EMBED_FIELD_VALUE'
}

Can someone help me ?
Thanks alot.

**Comment by DrSkunk** [comment]
Hiya @colbeagle , this is probably because the Discord.js library that's currently used needs to be updated. I currently don't have a plan for when to do this though, since it's a big chunk to do.
