### ISSUE TITLE
Error: Invalid gamemode loaded

### ISSUE THREAD

**Issue by GP128** [DrSkunk/discord-plays-pokemon#7]
Here's what I got when I tried doing "npm start"
"> discord-plays-pokemon@0.1.0 start
> tsc && node dist/index.js

C:\Users\user\Desktop\discord-plays-pokemon-main\dist\Config.js:22
    throw new Error('Invalid gamemode loaded');
    ^

Error: Invalid gamemode loaded
    at Object.<anonymous> (C:\Users\user\Desktop\discord-plays-pokemon-main\dist\Config.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\user\Desktop\discord-plays-pokemon-main\dist\index.js:46:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)

Node.js v19.3.0"

How do I make it work???

**Comment by Aurea-Juniper** [comment]
the node version is wrong use an older one
and put this in the console **`node dist/index.js`**
idk if it works but yes just try

**Comment by DrSkunk** [comment]
Indeed, I've been meaning to update this to use the new Discord API, since the reactions are quite slow.
